/**
 * @file 地区识别使用的城市、机场代码和别名替换表。
 * 按声明顺序替换为标准地区名称，各条正则分别保留大小写匹配规则。
 */

export const REGION_ALIASES = {
  香港: /Hongkong|HONG KONG|HKG|港(?!.*线)/gi,
  台湾: /新台|新北|TPE|TSA|台(?!.*线)/g,
  Taiwan: /Taipei/g,
  日本: /东京|大坂|NRT|HND|KIX|OSA|(深|沪|呼|京|广|杭|中|辽)日(?!.*(I|线))/g,
  Japan: /Tokyo|Osaka/g,
  韩国: /春川|首尔|ICN|GMP|韩(?!.*国)/g,
  Korea: /Seoul|Chuncheon/g,
  新加坡: /狮城|SIN|(深|沪|呼|京|广|杭)新/g,
  美国: /USA|LAX|SJC|SEA|SFO|JFK|EWR|IAD|ORD|DFW|MIA|ATL|IAH|PHX|DEN|LAS|BOS|Los Angeles|San Jose|Silicon Valley|Michigan|波特兰|芝加哥|哥伦布|纽约|硅谷|俄勒冈|西雅图|(深|沪|呼|京|广|杭)美/g,
  英国: /伦敦|LHR|LGW|STN|MAN|BHX|EDI|GLA/g,
  'United Kingdom': /UK|Great Britain|London/g,
  澳大利亚: /澳洲|墨尔本|悉尼|SYD|MEL|BNE|PER|ADL|CBR|(深|沪|呼|京|广|杭)澳/g,
  Australia: /Sydney|Melbourne/g,
  德国: /法兰克福|FRA|MUC|DUS|BER|HAM|STR|CGN|(深|沪|呼|京|广|杭)德(?!.*(I|线))/g,
  Germany: /Frankfurt/g,
  俄罗斯: /莫斯科|SVO|DME|LED|VKO/g,
  Russia: /Moscow/g,
  土耳其: /伊斯坦布尔|IST|SAW|ESB/g,
  Turkey: /Istanbul/g,
  印度: /孟买|BOM|DEL|BLR|MAA|CCU|HYD/g,
  India: /Mumbai/g,
  印尼: /印度尼西亚|雅加达|CGK|SUB|DPS/g,
  Indonesia: /Jakarta/g,
  法国: /巴黎|CDG|ORY|LYS|NCE|MRS/g,
  France: /Paris/g,
  Switzerland: /Zurich|ZRH|GVA/g,
  阿联酋: /迪拜|阿拉伯联合酋长国|DXB|AUH|SHJ/g,
  Dubai: /United Arab Emirates/g,
  泰国: /泰國|曼谷|BKK|DMK|HKT/g,
  中国: /中國/g,
  // 新增地区机场代码
  荷兰: /AMS/g,
  马来: /KUL|PEN|BKI/g,
  菲律宾: /MNL|CEB/g,
  加拿大: /YYZ|YVR|YUL|YYC|YEG|YOW/g,
  波兰: /WAW|KRK/g,
  捷克: /PRG/g,
  奥地利: /VIE/g,
  匈牙利: /BUD/g,
  比利时: /BRU/g,
  葡萄牙: /LIS|OPO/g,
  西班牙: /MAD|BCN/g,
  意大利: /FCO|MXP|VCE/g,
  挪威: /OSL/g,
  瑞典: /ARN/g,
  芬兰: /HEL/g,
  丹麦: /CPH/g,
  罗马尼亚: /OTP/g,
  以色列: /TLV/g,
  沙特阿拉伯: /RUH|JED/g,
  卡塔尔: /DOH/g,
  南非: /JNB|CPT/g,
  墨西哥: /MEX|CUN/g,
  阿根廷: /EZE/g,
  哥伦比亚: /BOG/g,
  巴西: /GRU|GIG/g,
};
