/**
 * @file 地区代码、中文名、英文名、旗帜及热门地区数据。
 * 记录顺序参与识别优先级；新增地区时填写完整记录，不调整已有顺序。
 */

/** 地区识别与输出标签所需的标准记录。 */
export interface Region {
  /** 标准地区代码。 */
  code: string;
  /** 中文地区名称，参与名称识别。 */
  chineseName: string;
  /** 英文地区名称，参与名称识别。 */
  englishName: string;
  /** 用于识别名称的地区旗帜。 */
  flag: string;
}

export const REGIONS: Region[] = [
  { code: 'CN', chineseName: '中国', englishName: 'China', flag: '🇨🇳' },
  { code: 'HK', chineseName: '香港', englishName: 'Hong Kong', flag: '🇭🇰' },
  { code: 'MO', chineseName: '澳门', englishName: 'Macao', flag: '🇲🇴' },
  { code: 'TW', chineseName: '台湾', englishName: 'Taiwan', flag: '🇹🇼' },
  { code: 'JP', chineseName: '日本', englishName: 'Japan', flag: '🇯🇵' },
  { code: 'KR', chineseName: '韩国', englishName: 'Korea', flag: '🇰🇷' },
  { code: 'SG', chineseName: '新加坡', englishName: 'Singapore', flag: '🇸🇬' },
  { code: 'US', chineseName: '美国', englishName: 'United States', flag: '🇺🇸' },
  { code: 'GB', chineseName: '英国', englishName: 'United Kingdom', flag: '🇬🇧' },
  { code: 'FR', chineseName: '法国', englishName: 'France', flag: '🇫🇷' },
  { code: 'DE', chineseName: '德国', englishName: 'Germany', flag: '🇩🇪' },
  { code: 'AU', chineseName: '澳大利亚', englishName: 'Australia', flag: '🇦🇺' },
  { code: 'AE', chineseName: '阿联酋', englishName: 'Dubai', flag: '🇦🇪' },
  { code: 'AF', chineseName: '阿富汗', englishName: 'Afghanistan', flag: '🇦🇫' },
  { code: 'AL', chineseName: '阿尔巴尼亚', englishName: 'Albania', flag: '🇦🇱' },
  { code: 'DZ', chineseName: '阿尔及利亚', englishName: 'Algeria', flag: '🇩🇿' },
  { code: 'AO', chineseName: '安哥拉', englishName: 'Angola', flag: '🇦🇴' },
  { code: 'AR', chineseName: '阿根廷', englishName: 'Argentina', flag: '🇦🇷' },
  { code: 'AM', chineseName: '亚美尼亚', englishName: 'Armenia', flag: '🇦🇲' },
  { code: 'AT', chineseName: '奥地利', englishName: 'Austria', flag: '🇦🇹' },
  { code: 'AZ', chineseName: '阿塞拜疆', englishName: 'Azerbaijan', flag: '🇦🇿' },
  { code: 'BH', chineseName: '巴林', englishName: 'Bahrain', flag: '🇧🇭' },
  { code: 'BD', chineseName: '孟加拉国', englishName: 'Bangladesh', flag: '🇧🇩' },
  { code: 'BY', chineseName: '白俄罗斯', englishName: 'Belarus', flag: '🇧🇾' },
  { code: 'BE', chineseName: '比利时', englishName: 'Belgium', flag: '🇧🇪' },
  { code: 'BZ', chineseName: '伯利兹', englishName: 'Belize', flag: '🇧🇿' },
  { code: 'BJ', chineseName: '贝宁', englishName: 'Benin', flag: '🇧🇯' },
  { code: 'BT', chineseName: '不丹', englishName: 'Bhutan', flag: '🇧🇹' },
  { code: 'BO', chineseName: '玻利维亚', englishName: 'Bolivia', flag: '🇧🇴' },
  {
    code: 'BA',
    chineseName: '波斯尼亚和黑塞哥维那',
    englishName: 'Bosnia and Herzegovina',
    flag: '🇧🇦',
  },
  { code: 'BW', chineseName: '博茨瓦纳', englishName: 'Botswana', flag: '🇧🇼' },
  { code: 'BR', chineseName: '巴西', englishName: 'Brazil', flag: '🇧🇷' },
  { code: 'VG', chineseName: '英属维京群岛', englishName: 'British Virgin Islands', flag: '🇻🇬' },
  { code: 'BN', chineseName: '文莱', englishName: 'Brunei', flag: '🇧🇳' },
  { code: 'BG', chineseName: '保加利亚', englishName: 'Bulgaria', flag: '🇧🇬' },
  { code: 'BF', chineseName: '布基纳法索', englishName: 'Burkina-faso', flag: '🇧🇫' },
  { code: 'BI', chineseName: '布隆迪', englishName: 'Burundi', flag: '🇧🇮' },
  { code: 'KH', chineseName: '柬埔寨', englishName: 'Cambodia', flag: '🇰🇭' },
  { code: 'CM', chineseName: '喀麦隆', englishName: 'Cameroon', flag: '🇨🇲' },
  { code: 'CA', chineseName: '加拿大', englishName: 'Canada', flag: '🇨🇦' },
  { code: 'CV', chineseName: '佛得角', englishName: 'CapeVerde', flag: '🇨🇻' },
  { code: 'KY', chineseName: '开曼群岛', englishName: 'CaymanIslands', flag: '🇰🇾' },
  { code: 'CF', chineseName: '中非共和国', englishName: 'Central African Republic', flag: '🇨🇫' },
  { code: 'TD', chineseName: '乍得', englishName: 'Chad', flag: '🇹🇩' },
  { code: 'CL', chineseName: '智利', englishName: 'Chile', flag: '🇨🇱' },
  { code: 'CO', chineseName: '哥伦比亚', englishName: 'Colombia', flag: '🇨🇴' },
  { code: 'KM', chineseName: '科摩罗', englishName: 'Comoros', flag: '🇰🇲' },
  { code: 'CG', chineseName: '刚果(布)', englishName: 'Congo-Brazzaville', flag: '🇨🇬' },
  { code: 'CD', chineseName: '刚果(金)', englishName: 'Congo-Kinshasa', flag: '🇨🇩' },
  { code: 'CR', chineseName: '哥斯达黎加', englishName: 'CostaRica', flag: '🇨🇷' },
  { code: 'HR', chineseName: '克罗地亚', englishName: 'Croatia', flag: '🇭🇷' },
  { code: 'CY', chineseName: '塞浦路斯', englishName: 'Cyprus', flag: '🇨🇾' },
  { code: 'CZ', chineseName: '捷克', englishName: 'Czech Republic', flag: '🇨🇿' },
  { code: 'DK', chineseName: '丹麦', englishName: 'Denmark', flag: '🇩🇰' },
  { code: 'DJ', chineseName: '吉布提', englishName: 'Djibouti', flag: '🇩🇯' },
  { code: 'DO', chineseName: '多米尼加共和国', englishName: 'Dominican Republic', flag: '🇩🇴' },
  { code: 'EC', chineseName: '厄瓜多尔', englishName: 'Ecuador', flag: '🇪🇨' },
  { code: 'EG', chineseName: '埃及', englishName: 'Egypt', flag: '🇪🇬' },
  { code: 'SV', chineseName: '萨尔瓦多', englishName: 'EISalvador', flag: '🇸🇻' },
  { code: 'GQ', chineseName: '赤道几内亚', englishName: 'Equatorial Guinea', flag: '🇬🇶' },
  { code: 'ER', chineseName: '厄立特里亚', englishName: 'Eritrea', flag: '🇪🇷' },
  { code: 'EE', chineseName: '爱沙尼亚', englishName: 'Estonia', flag: '🇪🇪' },
  { code: 'ET', chineseName: '埃塞俄比亚', englishName: 'Ethiopia', flag: '🇪🇹' },
  { code: 'FJ', chineseName: '斐济', englishName: 'Fiji', flag: '🇫🇯' },
  { code: 'FI', chineseName: '芬兰', englishName: 'Finland', flag: '🇫🇮' },
  { code: 'GA', chineseName: '加蓬', englishName: 'Gabon', flag: '🇬🇦' },
  { code: 'GM', chineseName: '冈比亚', englishName: 'Gambia', flag: '🇬🇲' },
  { code: 'GE', chineseName: '格鲁吉亚', englishName: 'Georgia', flag: '🇬🇪' },
  { code: 'GH', chineseName: '加纳', englishName: 'Ghana', flag: '🇬🇭' },
  { code: 'GR', chineseName: '希腊', englishName: 'Greece', flag: '🇬🇷' },
  { code: 'GL', chineseName: '格陵兰', englishName: 'Greenland', flag: '🇬🇱' },
  { code: 'GT', chineseName: '危地马拉', englishName: 'Guatemala', flag: '🇬🇹' },
  { code: 'GN', chineseName: '几内亚', englishName: 'Guinea', flag: '🇬🇳' },
  { code: 'GY', chineseName: '圭亚那', englishName: 'Guyana', flag: '🇬🇾' },
  { code: 'HT', chineseName: '海地', englishName: 'Haiti', flag: '🇭🇹' },
  { code: 'HN', chineseName: '洪都拉斯', englishName: 'Honduras', flag: '🇭🇳' },
  { code: 'HU', chineseName: '匈牙利', englishName: 'Hungary', flag: '🇭🇺' },
  { code: 'IS', chineseName: '冰岛', englishName: 'Iceland', flag: '🇮🇸' },
  { code: 'IN', chineseName: '印度', englishName: 'India', flag: '🇮🇳' },
  { code: 'ID', chineseName: '印尼', englishName: 'Indonesia', flag: '🇮🇩' },
  { code: 'IR', chineseName: '伊朗', englishName: 'Iran', flag: '🇮🇷' },
  { code: 'IQ', chineseName: '伊拉克', englishName: 'Iraq', flag: '🇮🇶' },
  { code: 'IE', chineseName: '爱尔兰', englishName: 'Ireland', flag: '🇮🇪' },
  { code: 'IM', chineseName: '马恩岛', englishName: 'Isle of Man', flag: '🇮🇲' },
  { code: 'IL', chineseName: '以色列', englishName: 'Israel', flag: '🇮🇱' },
  { code: 'IT', chineseName: '意大利', englishName: 'Italy', flag: '🇮🇹' },
  { code: 'CI', chineseName: '科特迪瓦', englishName: 'Ivory Coast', flag: '🇨🇮' },
  { code: 'JM', chineseName: '牙买加', englishName: 'Jamaica', flag: '🇯🇲' },
  { code: 'JO', chineseName: '约旦', englishName: 'Jordan', flag: '🇯🇴' },
  { code: 'KZ', chineseName: '哈萨克斯坦', englishName: 'Kazakstan', flag: '🇰🇿' },
  { code: 'KE', chineseName: '肯尼亚', englishName: 'Kenya', flag: '🇰🇪' },
  { code: 'KW', chineseName: '科威特', englishName: 'Kuwait', flag: '🇰🇼' },
  { code: 'KG', chineseName: '吉尔吉斯斯坦', englishName: 'Kyrgyzstan', flag: '🇰🇬' },
  { code: 'LA', chineseName: '老挝', englishName: 'Laos', flag: '🇱🇦' },
  { code: 'LV', chineseName: '拉脱维亚', englishName: 'Latvia', flag: '🇱🇻' },
  { code: 'LB', chineseName: '黎巴嫩', englishName: 'Lebanon', flag: '🇱🇧' },
  { code: 'LS', chineseName: '莱索托', englishName: 'Lesotho', flag: '🇱🇸' },
  { code: 'LR', chineseName: '利比里亚', englishName: 'Liberia', flag: '🇱🇷' },
  { code: 'LY', chineseName: '利比亚', englishName: 'Libya', flag: '🇱🇾' },
  { code: 'LT', chineseName: '立陶宛', englishName: 'Lithuania', flag: '🇱🇹' },
  { code: 'LU', chineseName: '卢森堡', englishName: 'Luxembourg', flag: '🇱🇺' },
  { code: 'MK', chineseName: '马其顿', englishName: 'Macedonia', flag: '🇲🇰' },
  { code: 'MG', chineseName: '马达加斯加', englishName: 'Madagascar', flag: '🇲🇬' },
  { code: 'MW', chineseName: '马拉维', englishName: 'Malawi', flag: '🇲🇼' },
  { code: 'MY', chineseName: '马来', englishName: 'Malaysia', flag: '🇲🇾' },
  { code: 'MV', chineseName: '马尔代夫', englishName: 'Maldives', flag: '🇲🇻' },
  { code: 'ML', chineseName: '马里', englishName: 'Mali', flag: '🇲🇱' },
  { code: 'MT', chineseName: '马耳他', englishName: 'Malta', flag: '🇲🇹' },
  { code: 'MR', chineseName: '毛利塔尼亚', englishName: 'Mauritania', flag: '🇲🇷' },
  { code: 'MU', chineseName: '毛里求斯', englishName: 'Mauritius', flag: '🇲🇺' },
  { code: 'MX', chineseName: '墨西哥', englishName: 'Mexico', flag: '🇲🇽' },
  { code: 'MD', chineseName: '摩尔多瓦', englishName: 'Moldova', flag: '🇲🇩' },
  { code: 'MC', chineseName: '摩纳哥', englishName: 'Monaco', flag: '🇲🇨' },
  { code: 'MN', chineseName: '蒙古', englishName: 'Mongolia', flag: '🇲🇳' },
  { code: 'ME', chineseName: '黑山共和国', englishName: 'Montenegro', flag: '🇲🇪' },
  { code: 'MA', chineseName: '摩洛哥', englishName: 'Morocco', flag: '🇲🇦' },
  { code: 'MZ', chineseName: '莫桑比克', englishName: 'Mozambique', flag: '🇲🇿' },
  { code: 'MM', chineseName: '缅甸', englishName: 'Myanmar(Burma)', flag: '🇲🇲' },
  { code: 'NA', chineseName: '纳米比亚', englishName: 'Namibia', flag: '🇳🇦' },
  { code: 'NP', chineseName: '尼泊尔', englishName: 'Nepal', flag: '🇳🇵' },
  { code: 'NL', chineseName: '荷兰', englishName: 'Netherlands', flag: '🇳🇱' },
  { code: 'NZ', chineseName: '新西兰', englishName: 'New Zealand', flag: '🇳🇿' },
  { code: 'NI', chineseName: '尼加拉瓜', englishName: 'Nicaragua', flag: '🇳🇮' },
  { code: 'NE', chineseName: '尼日尔', englishName: 'Niger', flag: '🇳🇪' },
  { code: 'NG', chineseName: '尼日利亚', englishName: 'Nigeria', flag: '🇳🇬' },
  { code: 'KP', chineseName: '朝鲜', englishName: 'NorthKorea', flag: '🇰🇵' },
  { code: 'NO', chineseName: '挪威', englishName: 'Norway', flag: '🇳🇴' },
  { code: 'OM', chineseName: '阿曼', englishName: 'Oman', flag: '🇴🇲' },
  { code: 'PK', chineseName: '巴基斯坦', englishName: 'Pakistan', flag: '🇵🇰' },
  { code: 'PA', chineseName: '巴拿马', englishName: 'Panama', flag: '🇵🇦' },
  { code: 'PY', chineseName: '巴拉圭', englishName: 'Paraguay', flag: '🇵🇾' },
  { code: 'PE', chineseName: '秘鲁', englishName: 'Peru', flag: '🇵🇪' },
  { code: 'PH', chineseName: '菲律宾', englishName: 'Philippines', flag: '🇵🇭' },
  { code: 'PT', chineseName: '葡萄牙', englishName: 'Portugal', flag: '🇵🇹' },
  { code: 'PR', chineseName: '波多黎各', englishName: 'PuertoRico', flag: '🇵🇷' },
  { code: 'QA', chineseName: '卡塔尔', englishName: 'Qatar', flag: '🇶🇦' },
  { code: 'RO', chineseName: '罗马尼亚', englishName: 'Romania', flag: '🇷🇴' },
  { code: 'RU', chineseName: '俄罗斯', englishName: 'Russia', flag: '🇷🇺' },
  { code: 'RW', chineseName: '卢旺达', englishName: 'Rwanda', flag: '🇷🇼' },
  { code: 'SM', chineseName: '圣马力诺', englishName: 'SanMarino', flag: '🇸🇲' },
  { code: 'SA', chineseName: '沙特阿拉伯', englishName: 'SaudiArabia', flag: '🇸🇦' },
  { code: 'SN', chineseName: '塞内加尔', englishName: 'Senegal', flag: '🇸🇳' },
  { code: 'RS', chineseName: '塞尔维亚', englishName: 'Serbia', flag: '🇷🇸' },
  { code: 'SL', chineseName: '塞拉利昂', englishName: 'SierraLeone', flag: '🇸🇱' },
  { code: 'SK', chineseName: '斯洛伐克', englishName: 'Slovakia', flag: '🇸🇰' },
  { code: 'SI', chineseName: '斯洛文尼亚', englishName: 'Slovenia', flag: '🇸🇮' },
  { code: 'SO', chineseName: '索马里', englishName: 'Somalia', flag: '🇸🇴' },
  { code: 'ZA', chineseName: '南非', englishName: 'SouthAfrica', flag: '🇿🇦' },
  { code: 'ES', chineseName: '西班牙', englishName: 'Spain', flag: '🇪🇸' },
  { code: 'LK', chineseName: '斯里兰卡', englishName: 'SriLanka', flag: '🇱🇰' },
  { code: 'SD', chineseName: '苏丹', englishName: 'Sudan', flag: '🇸🇩' },
  { code: 'SR', chineseName: '苏里南', englishName: 'Suriname', flag: '🇸🇷' },
  { code: 'SZ', chineseName: '斯威士兰', englishName: 'Swaziland', flag: '🇸🇿' },
  { code: 'SE', chineseName: '瑞典', englishName: 'Sweden', flag: '🇸🇪' },
  { code: 'CH', chineseName: '瑞士', englishName: 'Switzerland', flag: '🇨🇭' },
  { code: 'SY', chineseName: '叙利亚', englishName: 'Syria', flag: '🇸🇾' },
  { code: 'TJ', chineseName: '塔吉克斯坦', englishName: 'Tajikstan', flag: '🇹🇯' },
  { code: 'TZ', chineseName: '坦桑尼亚', englishName: 'Tanzania', flag: '🇹🇿' },
  { code: 'TH', chineseName: '泰国', englishName: 'Thailand', flag: '🇹🇭' },
  { code: 'TG', chineseName: '多哥', englishName: 'Togo', flag: '🇹🇬' },
  { code: 'TO', chineseName: '汤加', englishName: 'Tonga', flag: '🇹🇴' },
  { code: 'TT', chineseName: '特立尼达和多巴哥', englishName: 'TrinidadandTobago', flag: '🇹🇹' },
  { code: 'TN', chineseName: '突尼斯', englishName: 'Tunisia', flag: '🇹🇳' },
  { code: 'TR', chineseName: '土耳其', englishName: 'Turkey', flag: '🇹🇷' },
  { code: 'TM', chineseName: '土库曼斯坦', englishName: 'Turkmenistan', flag: '🇹🇲' },
  { code: 'VI', chineseName: '美属维尔京群岛', englishName: 'U.S.Virgin Islands', flag: '🇻🇮' },
  { code: 'UG', chineseName: '乌干达', englishName: 'Uganda', flag: '🇺🇬' },
  { code: 'UA', chineseName: '乌克兰', englishName: 'Ukraine', flag: '🇺🇦' },
  { code: 'UY', chineseName: '乌拉圭', englishName: 'Uruguay', flag: '🇺🇾' },
  { code: 'UZ', chineseName: '乌兹别克斯坦', englishName: 'Uzbekistan', flag: '🇺🇿' },
  { code: 'VE', chineseName: '委内瑞拉', englishName: 'Venezuela', flag: '🇻🇪' },
  { code: 'VN', chineseName: '越南', englishName: 'Vietnam', flag: '🇻🇳' },
  { code: 'YE', chineseName: '也门', englishName: 'Yemen', flag: '🇾🇪' },
  { code: 'ZM', chineseName: '赞比亚', englishName: 'Zambia', flag: '🇿🇲' },
  { code: 'ZW', chineseName: '津巴布韦', englishName: 'Zimbabwe', flag: '🇿🇼' },
  { code: 'AD', chineseName: '安道尔', englishName: 'Andorra', flag: '🇦🇩' },
  { code: 'RE', chineseName: '留尼汪', englishName: 'Reunion', flag: '🇷🇪' },
  { code: 'PL', chineseName: '波兰', englishName: 'Poland', flag: '🇵🇱' },
  { code: 'GU', chineseName: '关岛', englishName: 'Guam', flag: '🇬🇺' },
  { code: 'VA', chineseName: '梵蒂冈', englishName: 'Vatican', flag: '🇻🇦' },
  { code: 'LI', chineseName: '列支敦士登', englishName: 'Liechtensteins', flag: '🇱🇮' },
  { code: 'CW', chineseName: '库拉索', englishName: 'Curacao', flag: '🇨🇼' },
  { code: 'SC', chineseName: '塞舌尔', englishName: 'Seychelles', flag: '🇸🇨' },
  { code: 'AQ', chineseName: '南极', englishName: 'Antarctica', flag: '🇦🇶' },
  { code: 'GI', chineseName: '直布罗陀', englishName: 'Gibraltar', flag: '🇬🇮' },
  { code: 'CU', chineseName: '古巴', englishName: 'Cuba', flag: '🇨🇺' },
  { code: 'FO', chineseName: '法罗群岛', englishName: 'Faroe Islands', flag: '🇫🇴' },
  { code: 'AX', chineseName: '奥兰群岛', englishName: 'Ahvenanmaa', flag: '🇦🇽' },
  { code: 'BM', chineseName: '百慕达', englishName: 'Bermuda', flag: '🇧🇲' },
  { code: 'TL', chineseName: '东帝汶', englishName: 'Timor-Leste', flag: '🇹🇱' },
];

export const REGIONS_BY_CODE = new Map<string, Region>(
  REGIONS.map((region) => [region.code, region]),
);

// hot=true 的默认筛选范围，也是所有输出使用的排序优先级。
export const HOT_REGIONS = new Set<string>(['HK', 'TW', 'CN', 'JP', 'SG', 'US']);
